version: '3'

services:
  server:
    build: server/
    restart: always
    ports:
      - "8080:8080"
  pattern:
    build: pattern/
    restart: always
    links:
      - server:server
    environment:
      - TARGETSERVER=server
      - STREAMID=stream
    command: ./launchEncoderTestPattern.sh $TARGETSERVER $STREAMID

